phoenix-rtos/phoenix-rtos-lwip

- drivers/pppos.c
- modem/quectel/pppos_modem.h
The timeout value for the initial `AT` command was unnecessarily multiplied. This made lwip trip over and block for several hours if the modem had not responded immediately. The retry count was also decreased because there is no point in waiting so long for a modem which has woken improperly.
Even though `AT+QCFG="autopdn",0` command is issued, the modem usually errors out when trying to establish a PPP connection (by error, `ERROR` return code for `CONNECT` command is meant). Addition of `AT+CGATT=0` resulted in 100% success rate of PPP connections, compared to ~30% without `AT+CGATT=0`.
> Fix PPPoS driver and improve modem performance

- drivers/tuntap.c
- port/main.c
Accordingly to phoenix-rtos/libphoenix#70 (comment)
> Unify use of the rid parameter of msgRecv, msgRespond functions

- drivers/pppos.c
- port/sockets.c
New version hw/fw of modem changed their behavior – instead of hanging on AT_CONNECT_CMD now it returns error immediately if cannot do a connection yet. 
I added retrying connect command if doesn't timeouted. 
Also fixed some simple warnings
> pppos connect change

- port/sockets.c
This PR, combined with https://github.com/phoenix-rtos/libphoenix/pull/76 fixes loads of ugly warnings when building lwip, e.g.:
I know, the solution is hacky, but it seems like the simplest way to fix it without changing the whole idea of using both `libphoenix` and `lwip` headers in `phoenix-rtos-lwip/port/sockets.c`. However, I'm opened to comments and other ideas.
> port: Fix ioctl warnings

- Makefile
- _targets/Makefile.armv7m7-imxrt106x
- drivers/pppou.c
- port/main.c
This changes brings an easy support for the IoT, device to device, connections on `armv7m7-imxrt106x` target. The `ppp over uart`/serial driver can be used with virtually any `phoenix-rtos` target that support uart, that being said, enabling easy porting of the `phoenix-rtos-lwip` to other IoT targets. **Developing IoT applications can be easier even on targets without ethernet, bluetooth and wifi**, but with simple point-to-point serial/uart null-modem connection.  Why `pppou` instead of already present `pppos` driver?  The answer is simple as `pppos` support modem GSM/GPRS/LTE communication (Hayes AT-command chat) I don't want to break that functionality, so `pppou` safetly derived for a null-modem implementation that doesn't depend on any other things than `phoenix-rtos-lwip` and …
> Add armv7m7-imxrt106x LwIP target with device-to-device IoT communication driver

- include/default-opts/lwipopts.h
This is required by `ping` utility in order to set a timeout, when waiting for ICMP response.
> lwipopts: Allow setting socket Receive Timeout

- drivers/pppou.c
This PR enables fetch DNS address from a peer, when connecting via PPPoU.
An exemplary Linux command, which sets the DNS address for the peer:
`pppd /dev/ttyUSB0 460800 10.0.0.1:10.0.0 ms-dns 8.8.8.8 lock local nodetach noauth debug dump nocrtscts maxfail 0 holdoff 1`
> drivers/pppou: Enable using peer's DNS address

- port/devs.c
strcmp worked for "lo" by chance (next field after netif->name is zero)
JIRA: DTR-91
> dev: string compare fix

- port/devs.c
JIRA: G3-84
This change fixes building lwip, when IPv6 is enabled in lwipopts.h
This change is required in order to run IPv6 based projects including G3 Adaptation layer.
> port: Fix building when IPv6 enabled

- port/sockets.c
JIRA: RTOS-106
Fix typo in write size check. Use POSIX friendly SSIZE_MAX instead of home made INT_MAX.
> sockets: write size check fix

- wi-fi/whd/whd_resources.c
- wi-fi/whd/wifi_nvram_image.h
Currently two Wi-Fi modules are supported:
- AW-NM512 (CYW43439)
- Sterling-LWB (BCM4343W)
JIRA: DTR-235
> wi-fi: get FW, CLM and NVRAM based on chip id

- Makefile
Needed for the new Makefiles with header auto-install.
The problem was twofold:
- LOCAL_DIR value was invalid due to additional Makefile imports (and
defining component in root Makefile)
- the "include" dir consists of internal includes - not external API
JIRA: CI-59
> makes: don't install internal headers

- include/default-opts/lwipopts.h
- port/devs.c
JIRA: DTR-288
This change enables retrieving lwip statistics using `/dev/ipstats` device node. One has to set `LWIP_STATS` to 1 in a project's `lwipopts.h` file.
This change is useful for lwip debugging issues.
> port/devs: Provide statistics by reading from /dev/ipstats

- port/netpacket.c
Packets sent from netpacket socket were not captured by
netdump tool.
DONE: DTR-94
> netpacket: link output packets

- ipsec/ipsecdev.c
- port/devs.c
- port/sockets.c
printf("%2s", string); prints at least 2 characters from string printf("%.2s", string); prints at most 2 characters from string
Before fix in https://github.com/phoenix-rtos/libphoenix/pull/228 "%2s" used to work like "%.2s".
DONE: RTOS-403
> lwip: Fix incorrect use of printf %s

- drivers/physmmap.c
- wi-fi/hal/cyhal_sdio.c
JIRA: RTOS-665
Adjust mmap to POSIX standard.
https://github.com/phoenix-rtos/libphoenix/pull/306
> Adjust mmap calls to new interface

- wi-fi/hal/cyabs_rtos.c
- wi-fi/hal/cyhal_sdio.c
- wi-fi/hal/cyhal_sdio.h
- wi-fi/lwip/cybsp_wifi.c
- wi-fi/lwip/main.c
- wi-fi/whd/whd_management.c
> lwip/wifi: Fix crashes during reinitialisation of wi-fi

- drivers/Makefile
- drivers/ephy.c
- drivers/ephy.h
- drivers/imx6-enet-regs.h
- drivers/imx6-enet.c
- drivers/ephy: add MACPHY self-test
Add MACPHY test using local loopback mode
- drivers/ephy: add support for alternative configurations
- read / pass board revision to ephy_init
- add option for custom init hook to select alternative phy configuration
- rewrite RND/RNA ext config logic override
JIRA: DTR-480
Needed for DTRv2
> drivers/ephy: more dynamic support for KSZ8081 RNA/RND variants

- drivers/pppos.c
- drivers/pppou.c
Printing cfg as string should be safe as netif driver explicitly NULL terminate between arguments and argv should be null terminated too.
> drivers/(pppos, pppou): Fix warning

- drivers/netif-driver.c
- drivers/rtl8139cp.c
- include/route.h
- port/devs.c
- port/sockets.c
Provide IPv6 support. This includes:
* Some issues in lib-lwip (see PR that this one depends on)
* Fixing a bug in IPv6 ioctls
* Changing multicast filter flags in RTL8139 driver
* Provide IPv6 autonfiguration
For now I was working only on ia32-generic-qemu.
https://github.com/phoenix-rtos/lwip/pull/11
> Add support for IPv6

- Makefile
- port/sockets.c
Fixing compiler warnings introduced by https://github.com/phoenix-rtos/phoenix-rtos-lwip/pull/93
> Fix compiler warnings caused by enabling ipv6

- drivers/ephy.c
Warnings fixed:
```
Warning: /github/workspace/phoenix-rtos-lwip/drivers/ephy.c:121:9: warning: 'full_duplex' may be used uninitialized [-Wmaybe-uninitialized]
121 |         printf("lwip: ephy%u.%u link is %s %uMbps/%s (ctl %04x, status %04x, adv %04x, lpa %04x, pctl %04x,%04x)\n",
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
122 |                 phy->bus, phy->addr, linkup ? "UP  " : "DOWN", speed, full_duplex ? "Full" : "Half",
|                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
123 |                 bctl, bstat, adv, lpa, pc1, pc2);
|                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/github/workspace/phoenix-rtos-lwip/drivers/ephy.c:104:20: note: 'full_duplex' …
```
> misc: adapt to gcc 14.2 warnings
