phoenix-rtos/phoenix-rtos-lwip

drivers/pppos.c, port/threads.c
=> cppcheck errors

Makefile, drivers/pppos.c, modem/quectel/pppos_modem.h, modem/telit/pppos_modem.h
=> Ported to NOMMU, added support for another modem

port/threads.c
Stack size of collector thread should be parametrize against different platform and should be modified by opts.
=> Change collector stack size

Makefile, g3/g3_opts.h, g3/lbp_g3.c, g3/lbp_g3.h, g3/loadng_g3.c, g3/loadng_g3.h, g3/lowpan6_common.c, g3/lowpan6_common.h, g3/lowpan6_g3.c, g3/lowpan6_g3.h, port/sockets.c
Features specific for G3-PLC are a part of separate commits in order make it easier to upstream those changes, which are based on RFC's only.
=> Implement G3-PLC Adaptation Layer

drivers/pppou.c
With this fix, the `pppou` driver by default will add the `default-route`. When `default-route` is not to be added  `nodefault` configuration flag should be used
Add default route e.g.
```
app flash0 -x @lwip;pppou:/dev/uart3:115200:up xip1
```
Do not add default route e.g.
```
app flash0 -x @lwip;pppou:/dev/uart3:115200:up:nodefault xip1
```
=> pppou: Fix, set default route via ppp interface

_targets/Makefile.armv7a7-imx6ull
=> armv7a7-imx6ull: Remove pppos driver from supported drivers

include/netpacket.h, include/phoenix-hooks.h, port/netpacket.c, port/sockets.c
=> sockets: add packet sockets

_targets/Makefile.armv7m7-imxrt106x, drivers/pppos.c, modem/huawei/pppos_modem.h, modem/quectel/pppos_modem.h, modem/telit/pppos_modem.h
Those changes add support for Huawei E3372 modem in PPP mode using PPPoS driver already present in our lwip port.
Moreover, they allow automatic default route setting, raising the interface and fetching the DNS server, so the interface
is ready to use after plugging in the modem without any user's action.
This change is required in order to provide LTE network access on platforms with USB host support. The first platform, on which
I tested the solution is imxrt1064. Those changes won't work without a new USB Host Stack implementation and USB CDC ACM driver, which is currently under development.
=> Add support for Huawei E3372 LTE USB Modem in PPP mode

.github/workflows/ci.yml
=> ci: add rootfs artifact

port/main.c
Legacy code was incorrectly handling EOF (last read returns ERANGE)
and could potentially return corrupted data (state change between
reads).
JIRA: DTR-91
Required for route command. This version fixes EOF, can handle all buffer sizes and will not return corrupted data. It's not a perfect solution because access is limited to 1 reader/writer.
=> dev: lwip /dev/* entries refactor

include/netpacket.h, port/netpacket.c
- copy pbuf flags required to set sll_pkttype
- fix restoring ethernet header
- remove/restore ethernet header padding
- switch from ETHERTYPE_ALL to ETH_P_ALL
- small code style changes
JIRA: DTR-94
Required for netdump.
Requires:
https://github.com/phoenix-rtos/lwip/pull/7
https://github.com/phoenix-rtos/libphoenix/pull/114
=> netpacket: raw packet sockets fix

port/devs.c
JIRA: RTOS-78
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/155
=> dev: fix warning when LWIP_DNS = 0

Makefile, _targets/Makefile.armv7m7-imxrt106x, drivers/Makefile, drivers/g3plc.c, drivers/netif-driver.c, g3/Makefile, g3/g3_opts.h, g3/g3plc.h, g3/lbp_g3.c, g3/lbp_g3.h, g3/loadng_g3.c, g3/loadng_g3.h, g3/lowpan6_common.c, g3/lowpan6_g3.c, g3/lowpan6_g3.h, include/default-opts/g3/lwipopts.h, include/default-opts/lwipopts.h, include/netpacket.h, port/devs.c, port/main.c, port/netpacket.c, port/sockets.c, port/threads.c
=> g3: Add G3 driver for plugfest [WIP]

drivers/g3plc.c, g3/g3_opts.h, g3/loadng_g3.c, include/default-opts/g3/lwipopts.h
=> Quick fixes from plugfest [WIP]

.gitmodules
The source for contrib-lwip isn't available:
https://git.savannah.nongnu.org/git/lwip/lwip-contrib.git
JIRA: CI-102
=> change contrib-lwip source

wi-fi/lwip/main.c
=> wi-fi: add idle timeout

port/netpacket.c
=> netpacket: ethernet header padding fix

port/devs.c
JIRA: BES-197
This fixes building in projects, which do not use default lwipopts.h and don't define `LWIP_STATS` to any value.
=> port/devs: Fix building, when LWIP_STATS is not defined

wi-fi/hal/cyabs_rtos.c, wi-fi/hal/cyabs_rtos.h, wi-fi/hal/cyabs_rtos_impl.h
- support semaphore max value
- support semaphore get try
DONE: DTR-7
=> wi-fi: internal semaphore implementation based on libphoenix

port/threads.c
=> port/threads: sys_thread_join fix

.gitmodules
- remove contrib-lwip repository
- The repository has been unused for a long time and there were some problems with source server availability.
=> remove contrib-lwip repository

port/threads.c
=> port/threads.c: Use lwipopts.h defined priority for waittid thread

_targets/Makefile.armv7m7-imxrt117x
JIRA: NIL-303
- https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/335
- https://github.com/phoenix-rtos/phoenix-rtos-devices/pull/270
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/475
- https://github.com/phoenix-rtos/phoenix-rtos-build/pull/126
- https://github.com/phoenix-rtos/phoenix-rtos-project/pull/476
=> imxrt117x: Enable `pppou`, `pppos` net drivers with Huawei USB modem support

port/netpacket.c
=> netpacket: forward declaration fix

drivers/pppos.c, modem/esp8266/pppos_modem.h, modem/huawei/pppos_modem.h, modem/quectel/pppos_modem.h, modem/telit/pppos_modem.h
=> pppos: add support for ESP8266 Wi-Fi modem

modem/huawei/pppos_modem.h
=> modem/huawei: Set connection mode to LTE

port/threads.c
JIRA: RTOS-226
Make lwip compatible with fixed threadJoin
- JIRA: RTOS-226
=> lwip: fix threadJoin call

drivers/Makefile, modem/huawei/pppos_modem.h
JIRA: BES-241
- [ All new and existing linter checks and tests passed.
=> pppos: add option to set default APN externally at compile time

port/sockets.c
JIRA: RTOS-387
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/635
=> port/sockets.c: Adapt to change in ioctl_unpack

drivers/tuntap.c, port/main.c, port/sockets.c, wi-fi/lwip/main.c
=> Adapt to msgRecv, msgRespond API change

include/arch/cc.h, ipsec/sha256.c
=> add checks for unsupported byte order

drivers/imx6-enet.c, drivers/imx6ull-gpio.c, wi-fi/hal/cyhal_utils.h, wi-fi/lwip/main.c
=> update installed headers

.gitignore, drivers/tuntap.c, port/main.c, port/sockets.c, wi-fi/lwip/main.c
=> msg API changes

include/devs.h, include/filter.h, port/devs.c, port/filter.c, port/sockets.c, wi-fi/lwip/main.c
=> fix warnings

drivers/pppos.c
JIRA: NIL-588
Allow customization of `PPPOS_USE_BLOCKING_READ` flag, e.g. in `lwipopts.h` file.
=> drivers/pppos: allow customization of PPPOS_USE_BLOCKING_READ flag

drivers/pppos.c
Cherry-pick fixes from master branch into the 3.3 release branch:
- drivers/pppos: allow customization of PPPOS_USE_BLOCKING_READ flag
=> Cherry-pick changes for release 3.3

wi-fi/lwip/main.c
=> wi-fi: whd_wifi_get_associated_client_list() buffer fix

port/Makefile
Set the default stack size to 4 KB and make it configurable.
JIRA: RTOS-1156
=> port: customize main thread stack size
